name: doctests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install groq python-dotenv pytest coverage pytest-cov codecov

      - name: Run doctests with coverage
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pytest --doctest-modules --cov=. --cov-report=xml
          codecov